### PR TITLE
use phoenix endpoint if available

### PR DESCRIPTION
**Pull request by gordoneliel**
## Whats new

Uses phoenix_endpoint for link url generation if present in the conn.

Fixes https://github.com/ash-project/ash_json_api/issues/94

### Contributor checklist

- [x] Bug fixes include regression tests
- [x] Features include unit/acceptance tests

### CODE REVIEW

**Review by zachdaniel — DISMISSED** [review]

**Comment by zachdaniel** [comment]
LGTM, let me know if its ready to merge :)

**Comment by gordoneliel** [comment]
@zachdaniel Added a test. BTW seems a bit hacky referencing phoenix_endpoint here when we don't explicitly depend on phoenix? Also assumes there will be a .url() function in that module. Probably a better way with a callback or config of some sort in the future, thoughts?

**Comment by zachdaniel** [comment]
It's a bit weird but it's better than something more complex IMO

**Comment by gordoneliel** [comment]
@zachdaniel In a stalemate here. mix format requires parenthesis on the function call, credo does not want it

**Pull request merged**
