### PR TITLE
improvement: added route default_fields with test

### PR DESCRIPTION
**Pull request by tommasop**
PR linked to this discussion:
https://discord.com/channels/711271361523351632/1091730040699506750

Added minimal testing

### CODE REVIEW

**Comment by zachdaniel** [comment]
Looks great! Got some format/credo stuff to address. One of the `mix test` is going fail no matter what though, thats not your fault.

**Comment by tommasop** [comment]
Should have fixed the formatting issues, for the `credo` part l'll leave it up to you if you want to refactor the `serialize_attributes` function :)

**Comment by zachdaniel** [comment]
There are some failing tests, see the test task ending in (false, false)

**Comment by tommasop** [comment]
Done, thanks for your patience :)

**Review by zachdaniel — APPROVED** [review]

**Pull request merged**
