### PR TITLE
chore: Add CI matrix and ASH_VERSION

### PR DESCRIPTION
**Pull request by TheFirstAvenger**
chore: Add CI matrix and ASH_VERSION

Addresses https://github.com/ash-project/ash/issues/50

### CODE REVIEW

**Comment by TheFirstAvenger** [comment]
@zachdaniel This one is failing across the board with a complaint that controllers/response.ex isn't formatted correctly, but it is passing locally on my machine. Any ideas?

**Comment by zachdaniel** [comment]
That is *really* weird.

**Comment by zachdaniel** [comment]
It could potentially be the ex_check update.

**Comment by TheFirstAvenger** [comment]
@zachdaniel All set. I had put Elixir at 1.10.0 instead of 1.10.3. Changing that (and dropping Ash v1.8.0) made everything pass. Should be good to merge.

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀

**Pull request merged**
