### PR TITLE
Feat/open api spex helpers

### PR DESCRIPTION
**Pull request by mohammedzeglam-pg**
### Contributor checklist

- [ ] Bug fixes include regression tests
- [x] Features include unit/acceptance tests

### CODE REVIEW

**Comment by mohammedzeglam-pg** [comment]
it still need tests for delete/update and give me a review and still need this
https://github.com/ash-project/ash_json_api/pull/64#issuecomment-1399198801

**Comment by zachdaniel** [comment]
Hey there, so I like the idea of making a single open api module, but I don't think we should serve it from an individual route. If we make a single one, we should instead do something like this in the router:

```elixir
open_api "/open_api", apis: [Api1, Api2, Api3]
```

**Comment by mohammedzeglam-pg** [comment]
> ```elixir
> open_api "/open_api", apis: [Api1, Api2, Api3]
> ```

so the idea it is not to serve them from same router the idea just make api know how generate open_api schema instead of write new module for every api

**Comment by zachdaniel** [comment]
Yeah, what I'm getting at is that if each api has its own open api setup, then end-users will need to go through multiple open api specifications. Whereas you should be able to set up one open api specification for a list of apis. So that you have one `/open_api` route with all of your apis combined (if you want).

**Comment by mohammedzeglam-pg** [comment]
> Yeah, what I'm getting at is that if each api has its own open api setup, then end-users will need to go through multiple open api specifications. Whereas you should be able to set up one open api specification for a list of apis. So that you have one `/open_api` route with all of your apis combined (if you want).

Genius as usual

**Comment by zachdaniel** [comment]
Superseded by https://github.com/ash-project/ash_json_api/pull/72

**Pull request closed without merging**
